apiVersion: hazelcast.com/v1alpha1
kind: WanReplication
metadata:
  name: wan-replication
spec:
  resources:
    - name: hazelcast-first
      kind: Hazelcast
  targetClusterName: dev
  synConsistencyCheckStrategy: "MERKLE_TREES"
  endpoints: "<SECOND-CLUSTER-EXTERNAL-IP>"